<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'sales','controller'=>'index','action'=>'index'));
	$url_new = $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'add'));
?>
<title><?php echo $tr->translate("ADD_QUOATATION");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_QUOATATION")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER_INFO");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("customer_id");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("LOCATION_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('branch_id');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php  echo $tr->translate("SALE_AGENT");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa fa-calendar"></i>
									<?php echo $form->getElement("saleagent_id");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("ORDER_DATE");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<i class="fa fa-calendar"></i><?php echo $form->getElement("order_date");?>
								</div>
							</div>
							
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("QUOATION_NO");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("txt_order"); ?></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12">
								<button type="button" class="btn red delete">
								<i class="fa fa-barcode"></i>
								<span>
								Scan </span>
								</button><select data-placeholder="Select..." class="form-control select2me" id="add_item" name="add_item" Onchange="getItemOrder();"  style="width:80% ;margin:0 auto; text-align: center;">
											<?php echo $this->items; ?>
								</select>
								<button type="button" class="btn red delete">
									<input type="checkbox" Onclick="Confirmmessage()" id="free" name="free" />
									<span>&nbsp;&nbsp;Free</span>
								</button>
							</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
											<td><?php echo $tr->translate("DEL");?></td>
											<td><?php echo $tr->translate("NUM");?></td>
											<td style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME_CAP");?></td>
											<td><?php echo $tr->translate("FREE");?></td>
											<td><?php echo $tr->translate("QTY_UNIT");?></td>
											<td><?php echo $tr->translate("QTY_PER_UNIT");?></td>
											<td><?php echo $tr->translate("QTY_ORDER");?></td>
											<td><?php echo $tr->translate("UNIT_PRICE_CAP");?></td>
											<td><?php echo $tr->translate("DISCOUNT");?></td>
											<td><?php echo $tr->translate("SUB_TOTAL_CAP");?></td>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
								<button class="btn btn-primary" type="button" id="new_item" onclick="addRow(1);" name= "new_followup" value="New">
													&nbsp;<img src="<?php echo BASE_URL?>/images/icon/new-row.png" alt=""/><?php echo $tr->translate("ADD");?>
								</button>
					</div>
						<!-- blog bottom -->
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("payment_name");?>
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("តម្លៃសរុប​ :");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("totalAmoun");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PRICE_CURRENCY");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("currency");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DISCOUNT");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("dis_value");?>
								       <input type="hidden" name="global_disc" id="global_disc"/>
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("ពន្ធ");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("total_tax");?>
								</div>
							</div>
							<label class="control-label col-md-2">សាច់ប្រាក់សរុប​ :<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("all_total");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PAID");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("paid");?>
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("BALANCE");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("remain");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-4">
								<div class="input-icon right">
									<button type="submit" class="btn yellow btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-4">
								<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
							<div class="col-md-4">
								<a href="<?php echo $this->baseUrl();?>/sales/quoatation/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
						</div>
						
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- end new product -->
<script>
var index5 = 0;num=0;
var option5 = '<?php echo $this->items; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
var index=1;
function addRow(item_id) {
	index5++; //var first = index5;
	index=index+1;
	for(i=1; i<index5; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
	}
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	if(index5 == 1) {
		template+='<td >&nbsp;</td>';
	} else {
		template+='<td ><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td  width="2%">'+index5+'</td>';
	template+='<td width="30%"><select class="form-control select2me" Onchange="ShowPopupProduct('+ index5 + ');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'<option></option></select>'+inp+'</td>';
	template+='<td ><input type="checkbox" onkeyup="getPriceFree('+index5+')" id="pricefree_'+index5+'" name="pricefree_'+index5+'"/> </td>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_'+index5+'" name="qty_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" onkeyup="calculatePrice('+index5+')" class="form-control" required="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td ><input type="text" onkeyup="calculatePrice('+index5+')" required="1" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" /><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
	template+='<td  width="5%"><input type="text" onkeyup="calculatePrice('+index5+')" value="0" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" /><input type="hidden" id="olddis_value_'+index5+'" name="olddis_value_'+index5+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
	template+='<td ><input type="text" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#item_id_"+index5).val(item_id);
	getQtyById(index5);
	if(free.checked){
		$("#pricefree_"+index5).attr({checked:'checked'});  
		$("#price"+index5).val(0);
		$("#price"+index5).attr('readonly','readonly');
		$("#dis-value"+index5).attr('readonly','readonly');
		$("#dis-value"+index5).val(0);
	}
	else{
		//$("#dis-value"+index5).val(0);
		//$('#dis_value').val(0);
		$('#global_disc').val(0);
		//getCurrentPrice(index5);
		$("#paid").val(0);
	}
	$("#row_order_0").remove();
}
<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyById(index){//use
				item_id=$("#item_id_"+index).val();
				qty_unit=$("#qty_unit_"+index).val();
				qty_per_unit=$("#qty_per_unit_"+index).val();
				if(qty_unit==null || qty_unit==""){
					if(qty_per_unit!==null && qty_per_unit!==""){
						$("#qty"+index).val(qty_per_unit);
					}
				}else{
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id},
						success: function(data){
							item_qty = $.parseJSON(data);			
							main_qty =$("#qty_unit_"+index).val();
							detail_qty =  $("#qty_per_unit_"+index).val();
							total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							$("#qty"+index).val(total_qty.toFixed(3));
						},
						error:function(e){
							//alert(e);
						}
				});
			}
}
$( document ).ready(function() {
	alert("ready loaded");
});
$( window ).load(function() {
    alert("load loaded");
}); 
function getItemOrder(){
	item_ids=$("#add_item").val();
	$('#add_item').val('').trigger("liszt:updated");
	if(item_ids==-1){
		return false;
	}
	addRow(item_ids);
	$("#add_item").val("");
}
var record_index= 1;
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = ($('#dis_value').val());
	if(discountValue==''){$('#dis_value').val(0);discountValue=0;}
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);
		}
		doRemain();
	}
}
function CalcualteTax() {
	$('#status').val();
}
function doRemain() {
	var all_total = $('#all_total').val();
	var paid = $('#paid').val();
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain').val(remain.toFixed(2));
	}	
}
function totalQty(index){
	calculatePrice(index);
	getQtyById(index);
}
function calculatePrice(index) {
	var qty = $('#qty'+index).val();
	var price = $('#price'+index).val();
	var total = price * qty;
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				
			}else{
				after_discount = total - discount;
			}
			$('#total'+index).val(after_discount.toFixed(2));
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total'+index).val(parseFloat(after_discount).toFixed(2));
		}
		netTotal();
	}
}
 var record_id = 1;
function ShowPopupProduct(product_id){
	item_id = $("#item_id_"+ product_id).val();
	record_id = product_id;
	if(item_id==-1){
		$('#productpopup').modal('show');
	}
	else{
		getQtyById(product_id);
	}
}
function getCustomerInfo(){
	v_id = $("#v_name").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}
<?php $url_add_vendor =  $this->url(array('module'=>'purchase','controller'=>'vendor','action'=>'add-vendor')); ?>
function addNewVendor(){
	var v_name  = $("#vendor_name").val();
	var contact = $("#txt_contact_name").val();
	var phone   = $("#v_phone").val();
	var address = $("#txt_address").val();
	var txt_mail= $("#txt_mail").val();
	validate_text('#vendor_name');
	$.ajax({
        url: "<?php echo $url_add_vendor;?>",
        type: "post",
        data: {'v_name':v_name,'contact':contact,'phone':phone,'address':address,'txt_mail':txt_mail},
        success: function(data){
            val = $.parseJSON(data);
	        $('#v_name').append($("<option></option>").attr("value",val['vid']).attr("selected",true).text(v_name));  
            $("#contact").val(contact);
            $("#txt_phone").val(phone);   
            $("#vendor_address").val(address);     
            document.getElementById("frmvendor").reset();
            HideDialogVendor();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
function AddLocation(){
	var location_id= $("#LocationId").val();
	if(location_id==-1){
		     AddNewLocation(true);
	  }	
}
<?php $url_code =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'check-purchaseno')); ?>
function CheckPOInvoice(){
				pur_no=$("#txt_order").val();
				if(pur_no=="" || pur_no ==null){
					return false;
				}
				else{
				$.ajax({
						url:"<?php echo $url_code;?>",
						type:"post",
						data:{'pur_no':pur_no},
						success: function(data){
							value = $.parseJSON(data);
							if(value=="" || value==null){
							}
							else{
								alert("Invoice number is exist !");
								$("#txt_order").css("border-color","red");
								$("#txt_order").val("");
							}
						},
						error:function(){
						}
					});
				}	
}
</script>	