<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->Form;
?>
<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'other','action'=>'edit',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title> <?php echo $tr->translate("LOAN_TYPE")?></title>
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
						<i class="fa fa-globe"></i><?php echo $tr->translate("ADD_LOCATION");?>
				</div>
				
			</div>
			<div class="portlet-body form">
				<form class="form-horizontal" method="post" action="<?php echo $url_new;?>" >
					<div class="form-body ">
						<div style="margin: 0 auto;" >
								<div class="form-group">
									<label class="col-md-2 control-label"><?php echo $tr->translate("TITLE");?></label>
									<div class="col-md-4">
										<?php echo $frm->getElement('title_en');?>
									</div>
													
								</div>
								<div class="form-group">
									<label class="col-md-2 control-label"><?php echo $tr->translate("TYPE");?></label>
									<div class="col-md-4">
										<?php echo $frm->getElement('type');?>
									</div>
													
								</div>
								<div class="form-group">
													
									<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
									<div class="col-md-4">
										<?php echo $frm->getElement('status');?>
									</div>
								</div>
								
							<div class="form-group">
	                            <div class="col-md-12 ">
	                                <button type="submit" name="save_new" class="btn green"><?php echo $tr->translate("SAVE_NEW");?></button>
	                                <button type="submit" name="save_close" class="btn default"><?php echo $tr->translate("SAVE_CLOSE");?></button>
	                            </div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

