<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("TRANSFER_LIST");?></title>
<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'adjust-stock','action'=>'transfer-stock',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'index','action'=>'delete-product',));
	$formFilter = $this->formFilter;
?>
<div class="right" style="padding:5px;">
	<form method="post" action="<?php echo $formFilter->getAction(); ?>">
		<div class="view-table shadow select" width="100%">
			
		</div>
	</form>
	<div style="position: relative; clear: both;">
		<div class="head_form">
			<?php echo $tr->translate("ADJUST_LIST");?>
		</div>
		<div class="contain_form">
			<?php echo $this->list; ?>
		</div>
	</div>
</div><!-- end .right -->