<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("ADJUST_LIST");?></title>
<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'adjust','action'=>'add',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'index','action'=>'delete-product',));
	$formFilter = $this->formFilter;
?>
<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("ADJUST_LIST");?>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
	<div style="position: relative; clear: both;">
		<div class="contain_form">
			<?php echo $this->list; ?>
		</div>
	</div>
</div><!-- end .right -->